steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-playground-boa/chefs-companion-repo/chefs-companion-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-playground-boa/chefs-companion-repo/chefs-companion-app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'chefs-companion-service'
  - '--image'
  - 'us-central1-docker.pkg.dev/gcp-playground-boa/chefs-companion-repo/chefs-companion-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'us-central1-docker.pkg.dev/gcp-playground-boa/chefs-companion-repo/chefs-companion-app'