steps:
# Build and push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${COMMIT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${COMMIT_SHA}']

# Create a Cloud Deploy release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'release-${SHORT_SHA}'
    - '--delivery-pipeline=${_PIPELINE_NAME}'
    - '--region=${_REGION}'
    - '--annotations=commit_sha=${COMMIT_SHA}'
    - '--images=${_IMAGE_NAME}=${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO_NAME}/${_IMAGE_NAME}:${COMMIT_SHA}'

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPO_NAME: chefs-companion-repo
  _IMAGE_NAME: chefs-companion
  _PIPELINE_NAME: chefs-companion-pipeline
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
