steps:
# Build container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ishamirulinda-sdlc/companion-app/backend:${SHORT_SHA}', '.']

images:
- 'us-central1-docker.pkg.dev/ishamirulinda-sdlc/companion-app/backend:${SHORT_SHA}'

options:
  requestedVerifyOption: VERIFIED
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
