apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chefs-companion
spec:
  template:
    spec:
      containers:
      - image: chefs-companion
        ports:
        - containerPort: 8080
